from ai import call_gpt

"""
AiHaikuGenerator.py
-------------------
Code in Place has a fun library they allow students to use
called 'ai' which can let programs enter prompts into ChatGPT.
This was a simple program but I wanted try it out.
"""

def main():
    """ Creates a Haiku generated by ChatGPT """
    name = input("Enter your name: ")
    topic = input("Enter a topic: ")
    print("Creating your haiku...")

    haiku = call_gpt(f"Create a haiku using the name {name} and the topic {topic}")
    print(haiku)


if __name__ == "__main__":
    main()